[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.24'
optimizer_runs = 800
via_ir = false
auto_detect_remappings = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./foundry-out" },
    { access = "read", path = "./script/config"},
]
evm_version = 'cancun'

